sonar.projectKey=marlonch_bookstore-platform
sonar.organization=marlonch
sonar.host.url=https://sonarcloud.io
sonar.exclusions=\
  **/dto/**,\
  **/*Dto.java,\
  **/*Application.java,\
  **/config/**,\
  **/mapper/**
